// ignore for now as we target the minimum Gradle / AGP versions required instead of the newest
updates.ignore = [
  { groupId = "org.gradle" },
  { groupId = "dev.gradleplugins" },
  { groupId = "com.android.tools.build" }
]
