name: 🐛 Bug Report
description: Report a bug you've encountered
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Description ...

        Reproduction steps
        1. Run XXX
        2. Notice XXX
        3. See/experience bug
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What OS are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other

  - type: input
    id: maven-version
    attributes:
      label: Version of Gradle
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Version of gradle-bloop
    validations:
      required: true

  - type: input
    id: bloop-version
    attributes:
      label: Version of Bloop
    validations:
      required: true
